# Generated by Django 4.2rc1 on 2023-03-23 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_title',
        ),
    ]
